version: "2"
linters:
  default: all
  disable:
    - bodyclose
    - cyclop
    - dupl
    - err113
    - exhaustive
    - exhaustruct
    - forbidigo
    - lll
    - mnd
    - nlreturn
    - noctx
    - paralleltest
    - rowserrcheck
    - sqlclosecheck
    - testpackage
    - tparallel
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/melchor629/traefik-error-page
    funlen:
      lines: -1
      statements: 50
    goconst:
      min-len: 5
      min-occurrences: 4
    gocyclo:
      min-complexity: 12
    godox:
      keywords:
        - FIXME
    govet:
      disable:
        - fieldalignment
      enable-all: true
    misspell:
      locale: US
    staticcheck:
      checks:
        - all
        - -ST1003
  exclusions:
    generated: lax
    rules:
      - linters:
          - funlen
          - goconst
          - godot
        path: (.+)_test.go
      - path: (.+)\.go$
        text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
